### ISSUE TITLE
群晖docker安装，AssertionError错误，无法启动

### ISSUE THREAD

**Issue by tao0ps** [LogicJake/WebMonitor#11]
![20200309192225](https://user-images.githubusercontent.com/30834305/76208794-5cef4a80-623b-11ea-96c4-68051b531029.png)
AssertionError
AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x7fb59dfb0cf8> and <flask.blueprints.Blueprint object at 0x7fb5b4228cf8>. Both share the same name "bootstrap". Blueprints that are created on the fly need unique names.

环境变量开启了debug

**Comment by LogicJake** [comment]
很奇怪,我在play-with-docker.com能正常启动

**Comment by tao0ps** [comment]
重新安装启动刷新到sqlalchemy.exc.InternalError错误，我才想到是可能是数据库问题

新建数据库database，字符集要设置为utf8，启动成了，文档里提示下吧。(lll￢ω￢)

![20200309200527](https://user-images.githubusercontent.com/30834305/76211720-d4c07380-6241-11ea-908c-3fa3d278bed2.png)

**Comment by LogicJake** [comment]
感谢你的反馈

**Comment by raining1123** [comment]
> 重新安装启动刷新到sqlalchemy.exc.InternalError错误，我才想到是可能是数据库问题
> 
> 新建数据库database，字符集要设置为utf8，启动成了，文档里提示下吧。(lll￢ω￢)
> 
> ![20200309200527](https://user-images.githubusercontent.com/30834305/76211720-d4c07380-6241-11ea-908c-3fa3d278bed2.png)

群晖小白求教怎么设置数据库。。。。
![Snipaste_2020-03-13_09-31-41](https://user-images.githubusercontent.com/17892238/76581201-8fd06180-650d-11ea-8183-132da5ae30df.jpg)
