### ISSUE TITLE
采用css selector获取文本，选择器加上/::text后报错

### ISSUE THREAD

**Issue by ck7968** [LogicJake/WebMonitor#12]
Error: SelectorSyntaxError("Expected selector, got <DELIM '/' at 21>",)

**Comment by LogicJake** [comment]
给出报错网址和 css selector 内容

**Comment by ck7968** [comment]
https://www.amazon.com/dp/B07WNLB2RG

**Comment by ck7968** [comment]
https://www.amazon.com/dp/B07WNLB2RG

**Comment by ck7968** [comment]
#priceblock_saleprice/::text

**Comment by LogicJake** [comment]
看啦一下, 请求目标网站的时候跳到了robot检测页面,另外css有关文档错误,后续会修正.
正确的css应该是#priceblock_saleprice::text.感谢反馈

**Comment by LogicJake** [comment]
另外尝试使用无头浏览器能够抓取

**Comment by LogicJake** [comment]
![2020-03-10 18-46-23 的屏幕截图](https://user-images.githubusercontent.com/20673460/76305093-778af780-62ff-11ea-9ef0-e0da49db6a25.png)

**Comment by ck7968** [comment]
嗯，现在可以了，谢谢！

**Comment by vay1314** [comment]
> ![2020-03-10 18-46-23 的屏幕截图](https://user-images.githubusercontent.com/20673460/76305093-778af780-62ff-11ea-9ef0-e0da49db6a25.png)

请教这个测试工具在哪里？现在新加入规则只能等时间自动运行，很麻烦。

**Comment by vay1314** [comment]
> @vay1314已经放弃了

好吧，希望以后还能加回。目前测试规则很不方便

**Comment by zzz6839** [comment]
> > @vay1314已经放弃了
> 
> 好吧，希望以后还能加回。目前测试规则很不方便

+1 现在规则测试很不方便
