### ISSUE TITLE
启动的时候出错

### ISSUE THREAD

**Issue by Dawson0x00** [LogicJake/WebMonitor#13]
sudo python3 -m flask run -h 0.0.0.0 -p 5000
* Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
...................
...................
...................
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'example_url'

**Comment by LogicJake** [comment]
@Dawson0x00 修改配置文件 .env 的数据库地址

**Comment by Dawson0x00** [comment]
您好，可以加您qq 咨询下吗

**Comment by LogicJake** [comment]
@Dawson0x00 文档可以解决你的问题 https://www.logicjake.xyz/WebMonitor/#/install?id=%e6%b7%bb%e5%8a%a0%e9%85%8d%e7%bd%ae

**Comment by Dawson0x00** [comment]
好的 谢谢 ～ 看来我还需要搭建mysql服务器

**Comment by LogicJake** [comment]
@Dawson0x00 你也可以使用无需安装的sqlite, 如:DATABASE_URL=sqlite:///test.db 他在新建一个test.db作为数据库文件,而不需要额外安装mysql

**Comment by Dawson0x00** [comment]
嗯已经配置好 可以使用了～
