### ISSUE TITLE
小白又来乞讨教程了。。。

### ISSUE THREAD

**Issue by raining1123** [LogicJake/WebMonitor#15]
首先万分感谢开发者大大做出了docker image！
然而在群晖设置docker的数据库时我又傻眼了。。。
![Snipaste_2020-03-13_09-31-41](https://user-images.githubusercontent.com/17892238/76586561-20ae3980-651c-11ea-9794-189a82017551.jpg)

“:DATABASE_URL=sqlite:///test.db 他在新建一个test.db作为数据库文件,而不需要额外安装mysql”
“数据库也可以设置为无需安装的 sqlite，从而在本地新建文件存储数据。”
这两句话不知道怎么操作。。。请求指点。。。

**Comment by LogicJake** [comment]
@raining1123 群晖应该有界面化的环境变量设置

**Comment by LogicJake** [comment]
DATABASE_URL的值设置为sqlite:///test.db

**Comment by raining1123** [comment]
请问“卷”需要映射文件夹吗？
另外这个sqlite需要新建某个文件夹吗？

**Comment by raining1123** [comment]
万岁！！成功跑起来了！！

**Comment by LogicJake** [comment]
@raining1123 简单一点其实这种方式不需要你自己去新建文件夹或者文件,他会自动去创文件,但这种方式销毁容器数据库文件也丢了,我觉得可以映射到本地文件,虽然我不太懂咋操作.
