### ISSUE TITLE
正则表达式无法去除HTML标签

### ISSUE THREAD

**Issue by raining1123** [LogicJake/WebMonitor#16]
### 目标网站地址
http://www.gusu.gov.cn/qyfw/QiFuWang/GongGao?timeorder=1&reduorder=-1

### css selector / xpath 内容
css: .gonggao_article

### 实际发生了什么？
加::text无法提取文字
不加的话显示一堆HTML标签
用了N种正则都没有办法去除

**Comment by LogicJake** [comment]
因为文字属于gonggao_article子element的,所以需要进一步细化,建议监控标题,如
```.gonggao_article > span::text```
