### ISSUE TITLE
为程序增加jsonpath抓取和pushover推送

### ISSUE THREAD

**Issue by jacob2826** [LogicJake/WebMonitor#17]
嗨，我之前看到这个项目，非常喜欢。自己在本地为程序增加了jsonpath抓取和pushover推送。
我一直在本地合并这个项目的修改，但也想为这个项目做一些贡献。
如果可以，我想稍后把我的修改PR上来，不知道您是否介意？

**Comment by LogicJake** [comment]
@panfake 非常欢迎
