### ISSUE TITLE
请求增加docker的自定义端口号

### ISSUE THREAD

**Issue by dgrenti** [LogicJake/WebMonitor#24]
请求增加docker的自定义端口号，目前只能使用作者的5000,能否自定为任意端口号？另外如果是监控价格的话，能否做到例如少于n时，才发出邮件提醒之类的?

**Comment by LogicJake** [comment]
端口可以自定义哈，port参数改一下

**Comment by LogicJake** [comment]
可以后续加上

**Comment by LogicJake** [comment]
-e PORT=80

**Comment by dgrenti** [comment]
> -e PORT=80

感谢回复！还有一个问题想咨询一下的，就是说在docker上怎么备份对应的数据库呀！或者说是怎么把容器上的数据库文件映射到本地的路径，方便假如容器有问题了，数据库都没有了，请问这个怎么做吗?

**Comment by LogicJake** [comment]
@dgrenti 假如是用的sqlite，可以使用docker文件夹映射，从而持久化保存，-v参数，具体可以搜索

**Comment by dgrenti** [comment]
> @dgrenti 假如是用的sqlite，可以使用docker文件夹映射，从而持久化保存，-v参数，具体可以搜索

尝试使用 -v /data:/app/app/ 这样处理，但是会导致对应容器不断重启，无法启动；具体是要映射容器的哪个文件吗？找不到对应数据库的文件地址；如果是-v /data:/app/app/这个的话，会导致对应容器不能启动;

**Comment by LogicJake** [comment]
假设容器数据文件在/var，本机存在/var/db（确保已经存在），可以通过 -v /var/db:/var 进行映射，然后数据库地址指定为DATABASE_URL=sqlite:////var/test.db
