### ISSUE TITLE
创建了几个无头浏览器的监控任务后，跑了一段时间内存占用很高

### ISSUE THREAD

**Issue by ck7968** [LogicJake/WebMonitor#25]
创建了几个无头浏览器的监控任务后，跑了一段时间，有多个phantomjs进程并且内存占用很高，有没有办法优化？

**Comment by nabule** [comment]
app/main/selector/phantomjs_selector.py， 50行driver.close() 改为driver.quit()  内存占用情况有改善。

**Comment by ck7968** [comment]
好的，谢谢，我试下

**Comment by LogicJake** [comment]
@nabule 好的，晚上我更新下
