### ISSUE TITLE
能否接受多个邮件接收?

### ISSUE THREAD

**Issue by dgrenti** [LogicJake/WebMonitor#26]
接收邮件，能否写多个邮箱，能接收告警邮件吗?

**Comment by LogicJake** [comment]
@dgrenti 目前不支持

**Comment by dgrenti** [comment]
如果像价格那一块，能否做到当监控值达到标准时才发送提醒？如x=50,当x<=40时，发送提醒?这种情景!

**Comment by dgrenti** [comment]
> @dgrenti 目前不支持

了解!

**Comment by LogicJake** [comment]
@dgrenti 后期(可能明天支持

**Comment by dgrenti** [comment]
> @dgrenti 后期(可能明天支持
rss提示如下，随意一下rss都是这种提示，不知何解?
UnboundLocalError("local variable 'content' referenced before assignment",)
--
