### ISSUE TITLE
想问下这是什么原因?

### ISSUE THREAD

**Issue by a1ices** [LogicJake/WebMonitor#27]
![](https://loecho.oss-cn-beijing.aliyuncs.com/BlogImg20200418202814.png)

**Comment by LogicJake** [comment]
hahha，不好意思，有个版本大改动，好像把测试镜像推到正式仓库了

**Comment by a1ices** [comment]
哈好的 我自己重新dockerfile 生成一下

**Comment by LogicJake** [comment]
我重新构件好了，可以重新拉一下，或者等我晚上发布全新版本

**Comment by a1ices** [comment]
好的,东西很棒,解决了我的需求,支持您!!
