### ISSUE TITLE
数据抓取不到

### ISSUE THREAD

**Issue by ck7968** [LogicJake/WebMonitor#29]
你好，我这边有个后台系统，里面有部分表单的数据是从服务端异步获取的，代码参见附件，里面的5.0这个数据我始终获取不到，请问这个应该怎样设置？
<img width="618" alt="Xnip2020-04-26_18-20-19" src="https://user-images.githubusercontent.com/34849930/80304754-b0692800-87ea-11ea-964c-cd30ff43aec9.png">

**Comment by LogicJake** [comment]
异步数据request无法直接获取，可以尝试使用无头浏览器或者尝试直接读取异步接口。

**Comment by ck7968** [comment]
> 异步数据request无法直接获取，可以尝试使用无头浏览器或者尝试直接读取异步接口。

无头浏览器也获取不到。。

**Comment by LogicJake** [comment]
方便的话可以贴出网址，否则也不知道啥原因

**Comment by ck7968** [comment]
我发你邮箱，你帮忙看下吧，谢谢啦
