### ISSUE TITLE
使用正则表达式出现此问题，上次运行结果报错IndexError('tuple index out of range',)

### ISSUE THREAD

**Issue by nabule** [LogicJake/WebMonitor#32]
### 目标网站地址
http://www.cnnvd.org.cn/web/vulnerability/querylist.tag
### css selector / xpath 内容
xpath /html/body/div[4]/div/div[1]/di
### 实际发生了什么？
上次运行结果 
IndexError('tuple index out of range',)
### 部署相关信息
手动 or docker
docker

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| phantomjs version       |               |
| if Docker, version |               |

### 已排除原因
- [ x] 尝试使用无头浏览器抓取
- [ ] 网站反爬

### 额外信息（日志、报错等）
使用老版本正常，新版本有此问题。

配置文件
```
{
        "name": "CNNVD_ALL",
        "url": "http://www.cnnvd.org.cn/web/vulnerability/querylist.tag",
        "selector_type": 0,
        "selector": "/html/body/div[4]/div/div[1]/div",
        "is_chrome": 1,
        "frequency": 60,
        "create_time": "2020-06-28 09:53:24",
        "notification": "1",
        "regular_expression": "\u4e2d\u5371|\u9ad8\u5371|\u8d85\u5371",
        "rule": "",
        "headers": ""
    },
```

**Comment by nabule** [comment]
发现只要使用正规就会出此问题

**Comment by LogicJake** [comment]
@nabule 最近有点忙，可以要晚点修
