### ISSUE TITLE
监控规则在首次抓取时无法处理小数？

### ISSUE THREAD

**Issue by if1y** [LogicJake/WebMonitor#42]
数据为**小数**，**已使用正则**提取转换。

使用监控规则 `-decrease 0` 始终报错 `ValueError('could not convert string to float: ',)`；
无奈**暂时去除监控规则，成功抓取**。

之后**再加回监控规则，也不再报错**。

---

事情还是比较奇怪的，可能还需要后续等数据变动了再观察。

**Comment by if1y** [comment]
后续测试已出，监测和提醒都正常。

看来确实是 **首次抓取无法处理小数**。

**Comment by LogicJake** [comment]
咕咕咕，过年之前一定修
