### ISSUE TITLE
需求讨论

### ISSUE THREAD

**Issue by WYEEE** [LogicJake/WebMonitor#47]
1、请求对通知软件slack、tg_bot的支持，目前微信推送最灵敏方便，但不能打开推送内容，pushover和bark设置有点复杂，交互体验也不太好，slack集大成者，可以添加多种app服务，可以编辑推送内容，有时候网页变动xpath抓取的东西乱七八糟，在slack可以自定义推送内容，比如目标主站的网址，点击即跳转。
2、请求自由上传更改管理页面“I AM WATCH YOU”标题和LOGO；
3、xpath抓东西可以分开抓吗，比如title抓一个，url抓一个，date抓一个，自定义文本填写一个，推送的时候选择性填写。有的网站需要直接跳转新增的url，有的网站需要跳转到自定义文本的主站，让推送消息变得规整美观，而不带乱七八糟的符号。

非专业性点评，仅供参考，目前食用非常方便，解决大问题，Thanks♪(･ω･)ﾉ！！

**Comment by iamvicliu** [comment]
3.强烈支持，希望可以多抓

**Comment by if1y** [comment]
3 我也想说来着，感觉作者最近挺忙，哈哈
1 的话最近更新已经实现了（自定义PUSH/GET，自己按文档写一下）

**Comment by LogicJake** [comment]
3的改动需要涉及到修改数据表字段，而且需要讨论一个问题，如果监控这么多字段，那么判断内容发生变化依哪个为准呢？

**Comment by iamvicliu** [comment]
应该是任意一个变化就算。

因为抓取的结果是   {a:a内容， b:b内容，c:c内容}这一个整体

**Comment by LogicJake** [comment]
这样说的话，那可以多开几个抓取字段，title，url，date和一个自定义，分别用{title}，{url}，{date}，{custom}，对于原来的消息体content，则可以用这四个字段来自由组合。

**Comment by LogicJake** [comment]
这样同时也可以实现有些人想要的消息体自定义格式的要求

**Comment by if1y** [comment]
我有点不太明白{title}，{url}，{date}，{custom}这几个字段的意思，多抓没问题，但是感觉不该被预定义，被局限化。
可能有理解偏差，求解释

个人觉得：
可以在原来的`元素选择器`字段使用某个不冲突的分隔符来实现多项监控（比如`;`？），也就不需要改数据库了结构了。
然后也许还有符号可以加进来，实现对多个抓取项目的命名区分。然后这个命名同时也可以用在自定义推送。

**Comment by LogicJake** [comment]
这个也挺好的，分隔符简单，较好的命名区分怎么整呢

**Comment by if1y** [comment]
看了一圈，`{}`应该是在三种选择器规则里都没有被用到的。

那我感觉可以把元素选择器的多抓模式改成类似 json 的结构。
然后考虑到**兼容只有一个选择器时的情况**，同时**使规则更美观易读**，也可以不用`;`分割，直接一行一条
```
字段名1{字段选择器规则1}
字段名2{字段选择器规则2}
字段名3{字段选择器规则3}
```

其实和目前`监控规则`已有的处理方式（`-规则 参数`）有异曲同工之处啦

一己之见，也许还有更好的处理方法~

**Comment by LogicJake** [comment]
需求3已经实现，欢迎各位使用从而进行充分测试，滑稽。

**Comment by LogicJake** [comment]
### 选择器
元素选择器类型可以选择 Xpath， Css selector 或 JsonPath。  

一行一个元素选择器，每一行的格式为：选择器名称{选择器内容}，例如：
```
title{//*[@id="id3"]/h3/text()}
url{//*[@id="id3"]/h3/text()}
```  

### 消息体模板
消息体模板可为空，如果为空，则按照元素选择器的定义顺序以制表符为间隔拼接为字符串。下面介绍消息体模板的使用方式，如果元素选择器的设置为：
```
title{//*[@id="id3"]/h3/text()}
url{//*[@id="id3"]/h3/text()}
```  
则消息体模板可以设置为：
```
{title}的网址是{url}
```
如果title对应的元素选择器提取的内容为“WebMonitor真棒”，url对应的元素选择器提取的内容为“https://www.logicjake.xyz/WebMonitor”，则得到的消息内容为“WebMonitor真棒的网址是https://www.logicjake.xyz/WebMonitor”。

**Comment by if1y** [comment]
刚想问新选择器定义 `url` 后是否影响原有链接，就发现更新了 `url` 为系统保留字段

初步实测需要把元素选择器的文本框改为多行文本框，目前是单行文本框，无法直接录入回车

另外想问，是否兼容旧版选择器规则，即只输入 `{}` 中的内容，此时抓取数据默认为 `{content}`，网页标题为 `{header}`

**Comment by LogicJake** [comment]
@if1y 可以回车啊。的确需要兼容旧版额

**Comment by if1y** [comment]
已 pull 最新镜像，测试回车是直接保存了监控项目，没有录入到选择器的文本框中去

**Comment by LogicJake** [comment]
和截图这个一样吗
![Uploading image.png…]()

**Comment by LogicJake** [comment]
我的锅，数据库字段修改脚本没加

**Comment by if1y** [comment]
![image](https://user-images.githubusercontent.com/32222791/106442942-e2649480-64b6-11eb-82e7-cd802edda41c.png)

以防万一再次使用最新镜像重建容器，现在是报错，查看不了界面（看起来是字段问题）

**Comment by LogicJake** [comment]
@if1y 是的，数据库字段变了，稍等我更新一下

**Comment by LogicJake** [comment]
几乎都做完了，新需要开单独issue追踪
