### ISSUE TITLE
最近一次更新？后 时不时不执行任务

### ISSUE THREAD

**Issue by gq20110204** [LogicJake/WebMonitor#51]
**bug复现**
最近一次更新？后 时不时不执行任务
设置1分钟执行一次的任务 有时隔了10分钟才执行 有时1分钟后正确执行
日志里面看 一次执行完后有添加定时任务动作 但到了应该执行的时间却无动静
（我同时跑了好几个任务 其他任务也有一样的情况
**复现**
建个php显示当前时间 设置1分钟爬一次
**截图**
![QQ截图20210115180835](https://user-images.githubusercontent.com/22221191/104711906-e8d7da00-575c-11eb-8167-9058a3131ebd.png)
![DA77AB743419E6B1CE88511D08970898](https://user-images.githubusercontent.com/22221191/104711941-f3926f00-575c-11eb-80ec-af56617898f9.png)

**Comment by LogicJake** [comment]
客观存在，但具体错误原因不清楚，先pin看看有没有后来的人有更多信息。

**Comment by gq20110204** [comment]
看到别的issue有提到清理日志的问题
看了下我的数据库文件竟然有101M大 基本都是django_apscheduler_djangojobexecution这个表中的日志
然后我尝试清空了这个表 大小直接缩减到122KB 时不时不执行任务的问题也随之消失 跑了一晚上所有任务都正常执行
综上所述 考虑是不是由于数据库过大造成性能问题？

**Comment by LogicJake** [comment]
@gq20110204 这样一说有可能，这个是定时执行的三方包产生的表，而且sqlite数据库效率的确不高。

**Comment by gq20110204** [comment]
应该就是和日志过大有关 我清理后用了10天 没再出现过这样的问题
