### ISSUE TITLE
修改网页监控任务时的设置项不完整

### ISSUE THREAD

**Issue by if1y** [LogicJake/WebMonitor#53]
比如 通知方式 就没有地方可以修改。
如果确需修改，只能导出成文本并修改，再重新导入，很不方便。

**Comment by LogicJake** [comment]
![image](https://user-images.githubusercontent.com/20673460/106378302-90e8d680-63de-11eb-9939-2dd4fc246f32.png)
现行技术下，无法修改多选项

**Comment by if1y** [comment]
没事，那就将凑合用。

**Comment by LogicJake** [comment]
![image](https://user-images.githubusercontent.com/20673460/106380838-e1b4fb00-63ef-11eb-948f-4b63e4967aee.png)
点任务id会跳转到修改界面，里面可以改。

**Comment by if1y** [comment]
原来如此，没摸透😂
