### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by mrchenxxx** [LogicJake/WebMonitor#65]
用 docker pull 的时候 提示 `no matching manifest for linux/arm/v7 in the manifest list entries`
我是在树莓派上部署的docker

**Comment by LogicJake** [comment]
docker镜像只支持 linux/amd64,linux/arm64

**Comment by mrchenxxx** [comment]
> docker镜像只支持 linux/amd64,linux/arm64

谢谢
