### ISSUE TITLE
用户自定义post修改

### ISSUE THREAD

**Issue by ghztvb** [LogicJake/WebMonitor#70]
首先，感谢大佬的开源程序！！
在实际使用中，自定义post的时候
custom_notification.py的31行要修改吧
r = requests.post(url, json=json.loads(data))
r = requests.post(url, data=json.loads(data))
![image](https://user-images.githubusercontent.com/27721245/112256901-3e6dbd00-8c9f-11eb-9704-31f3291cf016.png)

**Comment by LogicJake** [comment]
https://zhuanlan.zhihu.com/p/144326157

**Comment by ghztvb** [comment]
抱歉，抱歉，是我自己的后台处理有问题！
