### ISSUE TITLE
正则表达式功能无法正常使用

### ISSUE THREAD

**Issue by nabule** [LogicJake/WebMonitor#8]
输入任何正则表达式均提示：
Error: Exception('无法使用正则提取',)

请给一个示例，多谢！

**Comment by LogicJake** [comment]
提示这个两种情况：源文本有错误或源文本没错，但使用给定的正则语句匹配不上。建议在源文本获取正确的前提下，利用在线正则匹配工具测试正则表达式。

**Comment by nabule** [comment]
经测试获取源文本正常，使用search或findall方法正常。
查询到match方法为“尝试从字符串的**起始位置**匹配一个模式”，个人觉得用search或者findall方法不限制起始位置更方便。
or 我使用的方法不对，有劳指正，谢谢！

**Comment by LogicJake** [comment]
@nabule 测试ok的，欢迎pr
