### ISSUE TITLE
如何测试 cookie有效

### ISSUE THREAD

**Issue by seanlvjie** [LogicJake/WebMonitor#90]
请问如何测试导出的cookie有效

我这边是抓取https://bankplus.jd.com/ 页面的内容，
1，为了测试cookie，xpath直接设置为 /html/body/string()
2，cookie为chrome复制出来，然后http://tools.bugscaner.com/cookietodict在线转换成 字典格式，并复制到“自定义请求头”的设置里
3，抓取出来的内容为“ 当前值为持有金额(元) 权益中心 电子账户 空空如也， 看看可转让的产品吧 正在加载… 没有更多了 市场 可转 明细 ......”
4，设置为无头浏览（关闭无头，无法抓取）

如果正常登陆了，持有金额应该是有数据的，猜测应该是cookie设置的有问题。

**Comment by nabule** [comment]
![image](https://user-images.githubusercontent.com/4198473/133010867-14ef0357-dac8-4031-97b5-c45321954549.png)
这样实测可以，注意格式。

**Comment by LogicJake** [comment]
不需要转化成字典格式，原始请求是什么就放什么
