### ISSUE TITLE
json抓取到string后报错

### ISSUE THREAD

**Issue by adrianzhang** [LogicJake/WebMonitor#94]
### 目标网站地址
不便透露

### css selector / xpath 内容
与问题无关

### 实际发生了什么？
获取的json中的值为string，监控规则里写了-less xxx。在任务状态中看到报错信息：
ValueError("could not convert string to float: '[xxx.xx]'",)

### 部署相关信息
手动 or docker
docker

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| phantomjs version       |               |
| if Docker, version |               |

### 已排除原因
- [x ] 尝试使用无头浏览器抓取
- [ x] 网站反爬

### 额外信息（日志、报错等）
见实际发生

**Comment by LogicJake** [comment]
@adrianzhang 这错误不是很明显嘛 抽取出来的带符号[]，不是纯数字
